#*
#*                  _    __ _ _
#*   __ _ ___  __ _| |_ / _(_) |___ ___  WEBSITE: https://goatfiles.github.io
#*  / _` / _ \/ _` |  _|  _| | / -_|_-<  REPOS:   https://github.com/goatfiles
#*  \__, \___/\__,_|\__|_| |_|_\___/__/  LICENCE: https://github.com/goatfiles/dotfiles/blob/main/LICENSE
#*  |___/
#*          MAINTAINERS:
#*              AMTOINE: https://github.com/amtoine antoine#1306 7C5EE50BA27B86B7F9D5A7BA37AAE9B486CFF1AB
#*              ATXR:    https://github.com/atxr    atxr#6214    3B25AF716B608D41AB86C3D20E55E4B1DE5B2C8B
#*

---
profiles:
  - name: ls
    registered_commands:
      - ls -1
      - ls -a
      - ls
    key_bindings:
      - key: d
        command: rm -rf $0
        confirm: true
      - key: o
        command: $HOME/scripts/open.sh $0
      - key: u
        command: cd $0

  - name: ls -l
    registered_commands:
      - ls -l
      - ls -la
      - ls -al
    key_bindings:
      - key: d
        command: rm -rf $8
        confirm: true
      - key: o
        command: $HOME/scripts/open.sh $8
      - key: u
        command: cd $8
    lines_to_skip: 1

  - name: git status --short
    registered_commands:
      - git status --short
      - git st
    key_bindings:
      - key: A
        command: git add $1
      - key: a
        command: git reset $1
      - key: d
        command: rm -rf $1
        confirm: true

  - name: git status
    registered_commands:
      - git status
    key_bindings:
      - key: A
        command: git add $0
      - key: a
        command: git reset $1
        confirm: true
        regex: ".*:\\s+([^\\s]+)"
      - key: d
        command: rm -rf $1
        confirm: true

  - name: docker ps
    registered_commands:
      - docker ps
    key_bindings:
      - key: s
        command: docker stop $0
        confirm: true
      - key: r
        command: docker restart $0
      - key: d
        command: docker kill $0
        confirm: true

  - name: git branch
    registered_commands:
      - git branch
    key_bindings:
      - key: c
        command: git checkout $1

  - name: git log
    registered_commands:
      - git log --pretty=oneline
    key_bindings:
      - key: c
        command: git checkout $0
      - key: o
        command: $HOME/scripts/open.sh $(git config --get remote.origin.url | sed 's/.git$//; s/git@github.com:/https:\/\/github.com\//')/commit/$0

  - name: lsof -iTCP | grep LISTEN
    registered_commands:
      - lsof -iTCP | grep LISTEN
      - lsof -iTCP
    key_bindings:
      - key: d
        command: kill -9 $1
        confirm: true
