cursor = '_'
env-vars = []
padding-x = 10
performance = "High"
window-opacity = 1.0
window-width = 1920
window-height = 1080
use-fork = true

[bindings]
    keys = [
        { key = 'u', with = "control | alt", action = "DecreaseFontSize" },
        { key = 'i', with = "control | alt", action = "IncreaseFontSize" },
        { key = 'o', with = "control | alt", action = "ResetFontSize" },

        { key = 'c', with = "control | shift", action = "Copy" },
        { key = 'v', with = "control | shift", action = "Paste" },
    ]

[fonts]
    size = 30

[developer]
    log-level = "INFO"

[navigation]
    mode = "Plain"
