#*
#*                  _    __ _ _
#*   __ _ ___  __ _| |_ / _(_) |___ ___  WEBSITE: https://goatfiles.github.io
#*  / _` / _ \/ _` |  _|  _| | / -_|_-<  REPOS:   https://github.com/goatfiles
#*  \__, \___/\__,_|\__|_| |_|_\___/__/  LICENCE: https://github.com/goatfiles/dotfiles/blob/main/LICENSE
#*  |___/
#*          MAINTAINERS:
#*              AMTOINE: https://github.com/amtoine antoine#1306 7C5EE50BA27B86B7F9D5A7BA37AAE9B486CFF1AB
#*              ATXR:    https://github.com/atxr    atxr#6214    3B25AF716B608D41AB86C3D20E55E4B1DE5B2C8B
#*

# https://starship.rs/config
format = """
$username\
$hostname\
$directory\
\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
\
$rust\
$python\
$lua\
$golang\
$c\
$zig\
${custom.nu}\
\
$battery\
$cmd_duration\
\
$character\
"""

right_format = ""
scan_timeout = 10
command_timeout = 100
add_newline = false

# https://starship.rs/config/#battery
[battery]
disabled = false

format             = "[$symbol$percentage]($style) "
full_symbol        = " "
charging_symbol    = " "
discharging_symbol = " "
unknown_symbol     = " "
empty_symbol       = " "

# https://starship.rs/config/#c
[c]
disabled = false

format = 'via [$name $version]($style)'

# https://starship.rs/config/#character
[character]
disabled = false

format         = "$symbol"
success_symbol = "[>](green) "
error_symbol   = "[x](bold red) "
vicmd_symbol   = "[V](bold green) "

# https://starship.rs/config/#command-duration
[cmd_duration]
disabled = false

format             = "took [$duration]($style) "
min_time           = 2_000
show_milliseconds  = false
style              = "bold yellow"
show_notifications = false
min_time_to_notify = 45_000

# https://starship.rs/config/#directory
[directory]
disabled = false

format            = "[$path]($style)[$read_only]($read_only_style) "
truncation_length = 3
truncate_to_repo  = true
style             = "bold cyan"
read_only         = "🔒"
read_only_style   = "red"
truncation_symbol = ""
repo_root_style   = "bold red"
home_symbol       = "~"

# https://starship.rs/config/#git-branch
[git_branch]
disabled = false

format = "[$symbol$branch]($style) "
symbol             = " "
truncation_length  = 50
truncation_symbol  = "…"
always_show_remote = false
only_attached      = true
style              = "bold yellow"

# https://starship.rs/config/#git-commit
[git_commit]
disabled = false

format             = "[\\($hash$tag\\)]($style) "
commit_hash_length = 7
style              = "bold green"
only_detached      = true
tag_disabled       = false
tag_symbol         = " 🏷 "

# https://starship.rs/config/#git-state
[git_state]
disabled = false

format       = '\([$state( $progress_current/$progress_total)]($style)\) '
rebase       = "REBASING"
merge        = "MERGING"
revert       = "REVERTING"
cherry_pick  = "[PICKING](bold red)"
bisect       = "BISECTING"
am           = "AM"
am_or_rebase = "AM/REBASE"
style        = "bold yellow"

# https://starship.rs/config/#git-metrics
[git_metrics]
disabled = false

format             = '([+$added]($added_style) )([-$deleted]($deleted_style) )'
added_style        = "bold green"
deleted_style      = "bold red"
only_nonzero_diffs = true

# https://starship.rs/config/#git-status
[git_status]
disabled = false

format     = '([\[$all_status$ahead_behind\]]($style) )'
conflicted = "="
ahead      = "⇡"
behind     = "⇣"
diverged   = "⇕"
up_to_date = "✓"
untracked  = "?"
stashed    = "\\$"
modified   = "!"
staged     = "+"
renamed    = "»"
deleted    = "✘"
style      = "bold red"

# https://starship.rs/config/#hostname
[golang]
disabled = false

format = 'via [🏎💨 $version](bold cyan) '

# https://starship.rs/config/#hostname
[hostname]
disabled = false

ssh_only = true
format = '[$ssh_symbol](bold blue) on [$hostname](bold red) '
trim_at = '.companyname.com'

# https://starship.rs/config/#lua
[lua]
disabled = false

format = 'via [🌕 $version](bold blue) '

# https://starship.rs/config/#python
[python]
disabled = false

format             = 'via [${symbol}${pyenv_prefix}(${version} )(\($virtualenv\) )]($style)'
version_format     = "v${raw}"
symbol             = "py "
style              = "yellow bold"
pyenv_version_name = false
pyenv_prefix       = "pyenv"
python_binary      = ["python", "python3", "python2"]
detect_extensions  = ["py"]
detect_files       = [".python-version", "Pipfile", "__init__.py", "pyproject.toml", "requirements.txt", "setup.py", "tox.ini"]
detect_folders     = []

# https://starship.rs/config/#rust
[rust]
disabled = false

format = 'via [⚙️ $version](red bold) '

# https://starship.rs/config/#username
[username]
disabled = false

style_user = 'yellow'
style_root = 'red bold'
format = '[$user]($style)'
show_always = false

# https://starship.rs/config/#zig
[zig]
disabled = false

format = 'via [⚡️](yellow bold)'

# https://starship.rs/config/#custom-commands
[custom.nu]
disabled = false

detect_files = ["package.nuon"]
detect_extensions = ["nu", "nush"]
shell = ["nu", "-c"]
command = "version | get version"
format = "via [nu $output](red bold) "
ignore_timeout = true
