[env]
TERM = "xterm-256color"

[font]
size = 20.0
normal = { family = "FiraCode Nerd Font Mono" }
bold = { family = "FiraCode Nerd Font Mono" }
italic = { family = "FiraCode Nerd Font Mono" }

[[keyboard.bindings]]
action = "ResetFontSize"
key = "I"
mods = "Alt|Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "O"
mods = "Alt|Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "U"
mods = "Alt|Control"
