import = ["~/.config/alacritty/theme.toml"]

[env]
TERM = "xterm-256color"

[font]
size = 21.0
normal = { family = "Monaspace Argon", style="Regular" }
bold = { family = "Monaspace Argon", style="Bold" }
italic = { family = "Monaspace Argon", style="Italic" }

[[keyboard.bindings]]
action = "ResetFontSize"
key = "I"
mods = "Alt|Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "O"
mods = "Alt|Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "U"
mods = "Alt|Control"
